### ISSUE TITLE
Add service to safe infrastructure

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-price-service#7]
- [ ] Mention the service in safe-infrastructure.
- [ ] If wallet infra team adds support for the service in the client gateway we could setup the service also.

**Comment by Uxio0** [comment]
@hectorgomezv @fmrsabino It would be posible to add the price service as an alternative API for the cgw? 

Ithink it could be useful so we can fallback if our provider does not support a network and we need to deploy the price service

**Comment by hectorgomezv** [comment]
I don't see any major downside to adding the Price Service as an alternative, it seems a good idea @Uxio0 🙂

Having that said, I would like to include some context:
- It seems the main goal of having this service as an alternative is to cover the case where a network is not supported by our current token prices provider. I think that's a valid reason. Just for context, I would like to say that we implemented the CGW prices client having in mind that it should work without an API Key for getting the token prices: using it in `safe-infrastructure` with no API Key would also work and prices would be retrieved (the provider rate-limits its free tier, of course).
- We dropped all the code related to rate conversions between fiat currencies (as our current provider does that job for us), and we also plan to cancel the subscription to the fiat rates provider we have been using in the past. I guess `safe-price-service` only gets USD prices, correct? If that's the case we need to either reconsider getting back the code and keep paying for the subscription, or either accept that when using `safe-price-service` as a fallback, only USD prices would be available, is that acceptable?

**Comment by Uxio0** [comment]
You are exposing 2 really good points @hectorgomezv . The idea for this service is not letting the logic of price calculation to be lost, and for the community to use and maintain this service. As it doesn't seem really straightforward to add support in the CGW for the reasons you are exposing, I wouldn't work on that unless:

- A lot of users demands it
- We need it for a network where our price provider is not working.

What do you think if we evaluate it in the future in case any of these conditions meet and I close this issue for now? (cc @moisses89 )
